app = "nicegui"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[build]
  dockerfile = "fly.dockerfile"
  #image = "zauberzeug/nicegui:0.9.25"

[env]

[deploy]
# boot a single, new VM with the new release, verify its health, then
# One by one, each running VM is taken down and replaced by the new release VM
strategy = "canary" 


[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 20
    soft_limit = 10
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "5s"
    restart_limit = 1
    timeout = "1s"

  [[services.http_checks]]
    interval = "20s"
    grace_period = "10s"
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 1
    timeout = "2s"
    tls_skip_verify = false
    [services.http_checks.headers]

  [[statics]]
    guest_path = "/app/nicegui/static"
    url_prefix = "/_nicegui/static"