[tool.poetry]
name = "nice_gui"
version = "0.1.0"
description = "High-Level Abstraction Web-GUI Using Just Python"
authors = ["Zauberzeug GmbH"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
justpy = "^0.1.5"

[tool.poetry.dev-dependencies]
debugpy = "^1.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
