name: Update Citation

on: [push]

# on:
#   release:
#     types:
#       - published

jobs:
  update_citation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyYAML

      - name: Update Citation.cff
        env:
          ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
        run: python .github/workflows/update_citation.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CITATION.cff
          git commit -m "Update citation.cff"
          git push
